// flow-typed signature: 625a4b1bdebc49d8c4c2e87bb98114fc
// flow-typed version: <<STUB>>/http2_v3.3.6/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http2/example/client' {
  declare module.exports: any;
}

declare module 'http2/example/server' {
  declare module.exports: any;
}

declare module 'http2/lib/http' {
  declare module.exports: any;
}

declare module 'http2/lib/index' {
  declare module.exports: any;
}

declare module 'http2/lib/protocol/compressor' {
  declare module.exports: any;
}

declare module 'http2/lib/protocol/connection' {
  declare module.exports: any;
}

declare module 'http2/lib/protocol/endpoint' {
  declare module.exports: any;
}

declare module 'http2/lib/protocol/flow' {
  declare module.exports: any;
}

declare module 'http2/lib/protocol/framer' {
  declare module.exports: any;
}

declare module 'http2/lib/protocol/index' {
  declare module.exports: any;
}

declare module 'http2/lib/protocol/stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http2/example/client.js' {
  declare module.exports: $Exports<'http2/example/client'>;
}
declare module 'http2/example/server.js' {
  declare module.exports: $Exports<'http2/example/server'>;
}
declare module 'http2/lib/http.js' {
  declare module.exports: $Exports<'http2/lib/http'>;
}
declare module 'http2/lib/index.js' {
  declare module.exports: $Exports<'http2/lib/index'>;
}
declare module 'http2/lib/protocol/compressor.js' {
  declare module.exports: $Exports<'http2/lib/protocol/compressor'>;
}
declare module 'http2/lib/protocol/connection.js' {
  declare module.exports: $Exports<'http2/lib/protocol/connection'>;
}
declare module 'http2/lib/protocol/endpoint.js' {
  declare module.exports: $Exports<'http2/lib/protocol/endpoint'>;
}
declare module 'http2/lib/protocol/flow.js' {
  declare module.exports: $Exports<'http2/lib/protocol/flow'>;
}
declare module 'http2/lib/protocol/framer.js' {
  declare module.exports: $Exports<'http2/lib/protocol/framer'>;
}
declare module 'http2/lib/protocol/index.js' {
  declare module.exports: $Exports<'http2/lib/protocol/index'>;
}
declare module 'http2/lib/protocol/stream.js' {
  declare module.exports: $Exports<'http2/lib/protocol/stream'>;
}
