// flow-typed signature: 5167727ebcf9a5928507c52189c67605
// flow-typed version: <<STUB>>/koa-mongo_v0.7.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-mongo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-mongo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-mongo/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-mongo/example.js' {
  declare module.exports: $Exports<'koa-mongo/example'>;
}
declare module 'koa-mongo/index' {
  declare module.exports: $Exports<'koa-mongo'>;
}
declare module 'koa-mongo/index.js' {
  declare module.exports: $Exports<'koa-mongo'>;
}
