// flow-typed signature: 5495fcf3386522dcbd28a663b65a8352
// flow-typed version: <<STUB>>/koa-json-error_v3.1.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-json-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-json-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-json-error/lib/defaults' {
  declare module.exports: any;
}

declare module 'koa-json-error/lib/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-json-error/index' {
  declare module.exports: $Exports<'koa-json-error'>;
}
declare module 'koa-json-error/index.js' {
  declare module.exports: $Exports<'koa-json-error'>;
}
declare module 'koa-json-error/lib/defaults.js' {
  declare module.exports: $Exports<'koa-json-error/lib/defaults'>;
}
declare module 'koa-json-error/lib/middleware.js' {
  declare module.exports: $Exports<'koa-json-error/lib/middleware'>;
}
