// flow-typed signature: 0f5e5044ea7aaf755c4a65d3f973b0da
// flow-typed version: <<STUB>>/koa-jsonp_v2.0.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-jsonp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-jsonp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-jsonp/dist/jsonp-stream' {
  declare module.exports: any;
}

declare module 'koa-jsonp/dist/jsonp' {
  declare module.exports: any;
}

declare module 'koa-jsonp/lib/jsonp-stream' {
  declare module.exports: any;
}

declare module 'koa-jsonp/lib/jsonp' {
  declare module.exports: any;
}

declare module 'koa-jsonp/test/jsonp.test' {
  declare module.exports: any;
}

declare module 'koa-jsonp/test/standard.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-jsonp/dist/jsonp-stream.js' {
  declare module.exports: $Exports<'koa-jsonp/dist/jsonp-stream'>;
}
declare module 'koa-jsonp/dist/jsonp.js' {
  declare module.exports: $Exports<'koa-jsonp/dist/jsonp'>;
}
declare module 'koa-jsonp/index' {
  declare module.exports: $Exports<'koa-jsonp'>;
}
declare module 'koa-jsonp/index.js' {
  declare module.exports: $Exports<'koa-jsonp'>;
}
declare module 'koa-jsonp/lib/jsonp-stream.js' {
  declare module.exports: $Exports<'koa-jsonp/lib/jsonp-stream'>;
}
declare module 'koa-jsonp/lib/jsonp.js' {
  declare module.exports: $Exports<'koa-jsonp/lib/jsonp'>;
}
declare module 'koa-jsonp/test/jsonp.test.js' {
  declare module.exports: $Exports<'koa-jsonp/test/jsonp.test'>;
}
declare module 'koa-jsonp/test/standard.test.js' {
  declare module.exports: $Exports<'koa-jsonp/test/standard.test'>;
}
