// flow-typed signature: 5f75994385f2ea4a16ed2cfe0e79ef32
// flow-typed version: <<STUB>>/koa-response-time_v2.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-response-time'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-response-time' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-response-time/index' {
  declare module.exports: $Exports<'koa-response-time'>;
}
declare module 'koa-response-time/index.js' {
  declare module.exports: $Exports<'koa-response-time'>;
}
